version = 0.1

[default.deploy.parameters]
stack_name = "serverless-todo-stack"
resolve_s3 = true
s3_prefix = "serverless-todo-stack"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
